joy:
  ros__parameters:
    # device_name: /dev/input/joypad-f710
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0
    coalesce_interval: 0.01
    sticky_buttons: false

joy_teleop:
  ros__parameters:
  #  default:
  #   type: topic
  #   interface_type: ackermann_msgs/msg/AckermannDriveStamped
  #   topic_name: teleop
  #   axis_mappings:
  #     drive-speed:
  #       axis: 4
  #       scale: 0.0
  #       offset: 0.0
  #     drive-steering_angle:
  #       axis: 0
  #       scale: 0.0
  #       offset: 0.0

    human_control:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      deadman_buttons: [6]
      axis_mappings:
        drive-speed:
          axis: 3
          scale: 1.0
          offset: 0.0
        drive-steering_angle:
          axis: 0
          scale: 0.34
          offset: 0.0

    autonomous_control:
      type: topic
      interface_type: std_msgs/msg/Bool
      topic_name: nav_control
      buttons: [7]
      message_value:
        data: 
          value: false